### ISSUE TITLE
Delete VOD'S older then {TIME}

### ISSUE THREAD

**Issue by Smallinger** [Zibbp/ganymede#115]
Hey, i think a cool features would be that you can setup  something to delete VOD's older then a specific time automatic.
and do a  optional statement like delete only vods that i have watched.

**Comment by Zibbp** [comment]
Hi,
Ganymede's goal is to be an archival platform and I do not believe automatic deletion of videos after X requirement fits that goal. Deleting a video in Ganymede does not delete the files so that feature wouldn't work.

Implementing something your self wouldn't be too hard. [API docs are available](https://github.com/Zibbp/ganymede/tree/main/docs) and expose the necessary information for you to script something yourself.

**Comment by Zibbp** [comment]
Got around to implementing a first iteration of this. Available in [v1.2.12](https://github.com/Zibbp/ganymede/releases/tag/v1.2.12)
