### ISSUE TITLE
Convert rendered chat into HLS

### ISSUE THREAD

**Issue by TheBinaryLoop** [Zibbp/ganymede#137]
Maybe add an option or extend the current HLS option to include the rendered chat, so that it can also be converted to HLS for easier web playback. Otherwise really great work you put into this piece of software. Love it.

**Comment by Zibbp** [comment]
The chat files are already relatively small (compared to the video files). Is load times the reason you would want HLS for the rendered chat? 
Also, just curious, do you prefer the rendered video chat rather than the newer "real time" chat playback?

**Comment by TheBinaryLoop** [comment]
I personally prefer the newer real time chat playback. But for compatibility reasons it would be nice to have everything in the same format. Another huge quality of live improvement would be a task to transform everything to either hls or mp4 wichever you chose as your storage format

**Comment by Zibbp** [comment]
The chat video files being small is why I didn't add HLS support and have no plan to do so. The task to transform hls <-> mp4 is complicated and would probably get no use which is why I don't want to spend the time developing it. This could be something you could hack together yourself with [tdarr](https://tdarr.io/) or [unmanic](https://github.com/Unmanic/unmanic). You would also need to update the video paths for each video to reflect the change.
