### ISSUE TITLE
Cannot create more than one channel

### ISSUE THREAD

**Issue by Entrivax** [Zibbp/ganymede#343]
I can't create a new channel with the "Create" button in the administration of channels.
It says the channel already exists.
I suspect a conflict between the frontend not allowing to specify an External Id, while requiring it to be unique in the database.
This is even more blocking by the fact there looks to be no way to edit that external id afterwards.

https://github.com/Zibbp/ganymede/assets/1197915/995f75fd-74e6-468b-a175-181bdd221987

https://github.com/Zibbp/ganymede-frontend/blob/9e6f34c0b1c0d09beba502b1531f9dd0668aaa3a/src/components/Admin/Channels/Drawer.tsx#L42-L48

https://github.com/Zibbp/ganymede/blob/1b4d5251cc2086ab2ea79f997298496730bd5495/internal/channel/channel.go#L40

https://github.com/Zibbp/ganymede/blob/1b4d5251cc2086ab2ea79f997298496730bd5495/ent/schema/channel.go#L21

**Comment by Zibbp** [comment]
Yep its failing to create the channel because of the issue you described. Fixes available in https://github.com/Zibbp/ganymede/pull/344 & https://github.com/Zibbp/ganymede-frontend/pull/20. I'll get these in a release either tonight or tomorrow. I don't allow updated the external ID as I use that in the backend quite a bit and don't want someone changing as it would break some functionality. If you'd like to change the external ID you'll need to do so via the database.

Fixes should be available on the `:main` image tags shortly if you want to test.

**Comment by Entrivax** [comment]
Looks good now, thank you!
I'm closing the issue.
