### ISSUE TITLE
VOD progress not loading on single VOD page

### ISSUE THREAD

**Issue by TheBinaryLoop** [Zibbp/ganymede#49]
The VOD progress is not loading on the VOD playing page. It is loading on the VOD list.

**Comment by Zibbp** [comment]
Hi,
I just released a new version of the frontend that should fix this issue. https://github.com/Zibbp/ganymede-frontend/releases/tag/v1.0.4

Do note, that it can take several seconds before it seeks to your saved progress due to the player needing to load both the VOD video and chat player which takes awhile depending on the size.
