### ISSUE TITLE
Is it possible to archive an entire channel (not just a single vod)?

### ISSUE THREAD

**Issue by Zibbp** [Zibbp/ganymede#60]
### Discussed in https://github.com/Zibbp/ganymede/discussions/59

<div type='discussions-op-text'>

<sup>Originally posted by **Snuupy** November 19, 2022</sup>
Love the software, glad I can archive some vods now that I want to keep.

I know there's the feature to watch a channel for _future_ uploads (and is currently discouraged due to #57), but I wanted to know if you could archive all vods available from a channel without having to manually enter every single vod ID. Thanks.</div>

**Comment by Zibbp** [comment]
Feature has been released in [v1.1.0](https://github.com/Zibbp/ganymede/releases/tag/v1.1.0), closing.

**Comment by CappiSteijns** [comment]
Sorry for re opening this issue.

I make use of this option:
![image](https://user-images.githubusercontent.com/84481241/217108621-d9de66c5-cc61-4823-bbbd-db0c06588b03.png)

The problem is this channel has ~785 VOD's resulting in the following error:
`2023-02-07T01:12:26+01:00 2023-02-07T01:12:26+01:00 ERR 2023-02-07T01:12:26+01:00 2023-02-07T01:12:26+01:00 ERR 2023-02-07T01:12:26+01:00 2023-02-07T01:12:26+01:00 ERR 2023-02-07T01:12:26+01:00 2023-02-07T01:12:26+01:00 ERR error getting videos | 2023-02-07T01:12:26+01:00 2023-02-07T01:12:26+01:00 ERR 2023-02-07T01:12:26+01:00 2023-02-07T01:12:26+01:00 ERR 2023-02-07T01:12:26+01:00 2023-02-07T01:12:26+01:00 ERR 2023-02-07T01:12:26+01:00 2023-02-07T01:12:26+01:00 ERR error getting videos | error=failed to get twitch videos: failed to get twitch videos: &{429 Too Many Requests 429 HTTP/2.0 2 0 map[Access-Control-Allow-Origin:[*] Content-Length:[143] Content-Type:[application/json; charset=utf-8] Date:[Tue, 07 Feb 2023 00:12:25 GMT] Ratelimit-Limit:[800] Ratelimit-Remaining:[0] Ratelimit-Reset:[1675728805] Strict-Transport-Security:[max-age=300] Timing-Allow-Origin:[https://www.twitch.tv] Vary:[Accept-Encoding] X-Cache:[MISS, MISS] X-Cache-Hits:[0, 0] X-Served-By:[cache-bfi-krnt7300063-BFI, cache-ams12759-AMS] X-Timer:[S1675728745.361873,VS0,VS0,VE161]] {0xc05fa5a180} 143 [] false false map[] 0xc05d3c5300 0xc0002c8630}`

Maybe some api limit? But it won't download an single VOD becuase of this error.

**Comment by Zibbp** [comment]
The pagination loop for requests with over 100 videos was pointing to the wrong variable causing it to repeat the same API request until it got rate limited. Pushed a fix in https://github.com/Zibbp/ganymede/commit/7a8a6e8a9acf5e00919ab765c4e2e9a9d47110dc. This fix has been released in [v1.2.3](https://github.com/Zibbp/ganymede/releases/tag/v1.2.3) which just got pushed out.
