### ISSUE TITLE
runtime error when restarting the "Chat Convert" task

### ISSUE THREAD

**Issue by fllppi** [Zibbp/ganymede#79]
hello,
with many of my live stream recordings, the "Chat Convert" task got stuck and there was no output in either the web interface or the container log. After restarting the task, the API container crashes and issues the following error:

```
panic: runtime error: slice bounds out of range [:41] with length 40

goroutine 381 [running]:
github.com/zibbp/ganymede/internal/utils.ConvertTwitchLiveChatToVodChat({0xc0000345a0, 0x44}, {0xc000395738, 0x4}, {0xc0003efa40, 0x24}, {0xc000394720, 0xb}, 0x2f68995, {0x1c05188, ...})
        /app/internal/utils/chat.go:259 +0x162a
github.com/zibbp/ganymede/internal/archive.(*Service).TaskLiveChatConvert(0xc000117f80, 0xc0005064b0, 0xc0005be8c0, 0xc00049fb80, 0x50?)
        /app/internal/archive/archive.go:916 +0x8fc
created by github.com/zibbp/ganymede/internal/archive.(*Service).TaskChatConvertRestart
        /app/internal/archive/archive.go:871 +0x186
```

The live chat files are all in the tmp folder mounted in the container, so nothing should be missing

**Comment by Zibbp** [comment]
Hi,
When the "Chat Convert" task gets "stuck" is it in the loading state with the loading circle or something else? If possible, can you upload all the relevant chat json files regarding this issue?

Does this happen for many streamers or just one stream? Does it happen every archive or seemly random?

**Comment by Zibbp** [comment]
It appears the slice bounds error is occurring because the convert function is trying to parse emotes in positions that are not there. For example this message ` dnfLogo dnfHerz dnfLogo dnfHerz dnfLogo` which is 40 characters long believes it has emotes in positions 50-60.
``` json
                "locations": [
                    "34-40",
                    "50-56"
                ]
```

This happens from time to time with [chat_downloader](https://github.com/xenova/chat-downloader). My check for the out of bounds emotes was not adding 1 more to the "position 2" of the emote location. With this change I was able to convert the two supplied chats which were previously having issues. I'm going to do some more testing to ensure everything is OK and push out a release.

**Comment by Zibbp** [comment]
@flip-k [Version 1.1.8](https://github.com/Zibbp/ganymede/releases/tag/v1.1.8) has been released which includes a fix that should work for your issue. Please update and give this a try to see if it fixes your problem.
